# Generated by Django 4.2.7 on 2026-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('bebida_principal', models.CharField(choices=[('agua', 'Agua'), ('vino', 'Vino'), ('cerveza', 'Cerveza'), ('sidra', 'Sidra'), ('otra', 'Otra')], default='agua', max_length=20)),
                ('refresco', models.CharField(blank=True, max_length=100, null=True)),
                ('alcohol', models.CharField(choices=[('ron', 'Ron'), ('vodka', 'Vodka'), ('whisky', 'Whisky'), ('ginebra', 'Ginebra'), ('ninguno', 'Ninguno'), ('otra', 'Otra')], default='ninguno', max_length=20)),
                ('dias', models.IntegerField(choices=[(1, 'Sábado'), (2, 'Domingo')], default=1)),
                ('ha_pagado', models.BooleanField(default=False)),
                ('cantidad_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
