# Generated by Django 4.2.7 on 2026-03-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='alcohol',
            field=models.CharField(choices=[('ron_barcelo', 'Ron Barceló'), ('ron_legendario', 'Ron Legendario'), ('ron_otro', 'Ron (Otro)'), ('whisky_dyc8', 'Whisky Dyc8'), ('whisky_red', 'Whisky Red Label'), ('whisky_otro', 'Whisky (Otro)'), ('ginebra_larios', 'Ginebra Larios'), ('ginebra_beefeater', 'Ginebra Beefeater'), ('ginebra_otro', 'Ginebra (Otra)'), ('vodka', 'Vodka'), ('ninguno', 'Ninguno'), ('otra', 'Otra')], default='ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='bebida_principal',
            field=models.CharField(choices=[('agua', 'Agua'), ('vino', 'Vino'), ('cerveza', 'Cerveza'), ('tinto_verano', 'Tinto de Verano'), ('rebujito', 'Rebujito'), ('otra', 'Otra')], default='agua', max_length=20),
        ),
    ]
