# Generated by Django 4.2.7 on 2026-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_alcohol_alter_persona_bebida_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='alcohol',
            field=models.CharField(choices=[('ron_barcelo', 'Ron Barceló'), ('ron_legendario', 'Ron Legendario'), ('whisky_dyc8', 'Whisky Dyc8'), ('whisky_red', 'Whisky Red Label'), ('ginebra_larios', 'Ginebra Larios'), ('ginebra_beefeater', 'Ginebra Beefeater'), ('vodka', 'Vodka'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='bebida_principal',
            field=models.CharField(choices=[('agua', 'Agua'), ('vino', 'Vino'), ('cerveza', 'Cerveza'), ('tinto_verano', 'Tinto de Verano'), ('rebujito', 'Rebujito')], default='agua', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dias',
            field=models.CharField(choices=[('sabado', 'Sábado'), ('domingo', 'Domingo'), ('ambos', 'Sábado y Domingo')], default='sabado', max_length=10),
        ),
    ]
