# Generated by Django 6.0.3 on 2026-03-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_alcohol_alter_persona_bebida_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida', models.CharField(choices=[('ron_barcelo', 'Ron Barceló'), ('ron_legendario', 'Ron Legendario'), ('whisky_dyc8', 'Whisky Dyc8'), ('whisky_red', 'Whisky Red Label'), ('ginebra_larios', 'Ginebra Larios'), ('ginebra_beefeater', 'Ginebra Beefeater'), ('vodka', 'Vodka')], max_length=20, unique=True)),
                ('cantidad_stock', models.IntegerField(default=0, verbose_name='Botellas en stock')),
            ],
            options={
                'verbose_name': 'Stock de Alcohol',
                'verbose_name_plural': 'Stock de Alcohol',
            },
        ),
        migrations.CreateModel(
            name='StockDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], default='ingreso', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Dinero',
                'verbose_name_plural': 'Movimientos de Dinero',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='persona',
            name='bebida_principal',
            field=models.CharField(choices=[('agua', 'Agua'), ('vino', 'Vino'), ('cerveza', 'Cerveza'), ('tinto_verano', 'Tinto de Verano'), ('rebujito', 'Rebujito'), ('tonica', 'Tónica (Exótica)')], default='agua', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='refresco',
            field=models.CharField(choices=[('coca_cola', 'Coca-Cola'), ('coca_cola_zero', 'Coca-Cola cero'), ('coca_cola_zero_zero', 'Coca-Cola cero cero'), ('fanta_naranja', 'Fanta Naranja'), ('fanta_limon', 'Fanta Limón'), ('sprite', 'Sprite'), ('aquarius', 'Aquarius'), ('tonica', 'Tónica'), ('nestea', 'Nestea'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
    ]
