# Generated by Django 6.0.3 on 2026-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_stockalcohol_stockdinero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cantidad_bebida_principal',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad bebida principal'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='alcohol',
            field=models.CharField(choices=[('ron_barcelo', 'Ron Barceló'), ('ron_legendario', 'Ron Legendario'), ('whisky_dyc8', 'Whisky Dyc8'), ('whisky_red', 'Whisky Red Label'), ('ginebra_larios', 'Ginebra Larios'), ('ginebra_beefeater', 'Ginebra Beefeater'), ('ginebra_exotic', 'Ginebra Exotic'), ('vodka', 'Vodka'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='bebida_principal',
            field=models.CharField(choices=[('agua', 'Agua'), ('vino', 'Vino'), ('cerveza', 'Cerveza'), ('tinto_verano', 'Tinto de Verano'), ('rebujito', 'Rebujito')], default='agua', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockalcohol',
            name='bebida',
            field=models.CharField(choices=[('ron_barcelo', 'Ron Barceló'), ('ron_legendario', 'Ron Legendario'), ('whisky_dyc8', 'Whisky Dyc8'), ('whisky_red', 'Whisky Red Label'), ('ginebra_larios', 'Ginebra Larios'), ('ginebra_beefeater', 'Ginebra Beefeater'), ('ginebra_exotic', 'Ginebra Exotic'), ('vodka', 'Vodka')], max_length=20, unique=True),
        ),
    ]
