# Generated by Django 6.0.3 on 2026-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_persona_cantidad_bebida_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cantidad_bebida_principal',
        ),
        migrations.AlterField(
            model_name='persona',
            name='bebida_principal',
            field=models.CharField(default='agua', max_length=200),
        ),
    ]
