# Generated by Django 6.0.3 on 2026-04-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_remove_persona_cantidad_bebida_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_guardados', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Objeto guardado',
                'verbose_name_plural': 'Objetos guardados',
                'ordering': ['objeto', 'persona__nombre', 'persona__apellidos'],
            },
        ),
        migrations.AlterField(
            model_name='persona',
            name='alcohol',
            field=models.CharField(choices=[('ron_barcelo', 'Ron Barceló'), ('ron_legendario', 'Ron Legendario'), ('whisky_dyc8', 'Whisky Dyc8'), ('whisky_red', 'Whisky Red Label'), ('ginebra_larios', 'Ginebra Larios'), ('ginebra_beefeater', 'Ginebra Beefeater'), ('ginebra_exotic', 'Ginebra Exotic'), ('ginebra_rives_1880', 'Ginebra Rives 1880'), ('vodka', 'Vodka'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='refresco',
            field=models.CharField(choices=[('coca_cola', 'Coca-Cola'), ('coca_cola_zero', 'Coca-Cola cero'), ('coca_cola_zero_zero', 'Coca-Cola cero cero'), ('fanta_naranja', 'Fanta Naranja'), ('fanta_limon', 'Fanta Limón'), ('sprite', 'Sprite'), ('aquarius', 'Aquarius'), ('power', 'Power'), ('tonica', 'Tónica'), ('nestea', 'Nestea'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockalcohol',
            name='bebida',
            field=models.CharField(choices=[('ron_barcelo', 'Ron Barceló'), ('ron_legendario', 'Ron Legendario'), ('whisky_dyc8', 'Whisky Dyc8'), ('whisky_red', 'Whisky Red Label'), ('ginebra_larios', 'Ginebra Larios'), ('ginebra_beefeater', 'Ginebra Beefeater'), ('ginebra_exotic', 'Ginebra Exotic'), ('ginebra_rives_1880', 'Ginebra Rives 1880'), ('vodka', 'Vodka')], max_length=20, unique=True),
        ),
    ]